### ISSUE TITLE
EDMX > Generate model from DataBase > clicking new connection button throws exception

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/EntityFramework6#1121]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/657192/edmx-generate-model-from-database-clicking-new-con.html)._

---
Whenever I open an EDMX file, and then select to generate the model from database the wizard pops up. When I click [New connection] it throws an exception, after which VS becomes unresponsive and must be restarted.

The exception is as follows:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Data.Entity.Infrastructure.Design.AppConfigReader.GetProviderService(String invariantName)
   at System.Data.Entity.Infrastructure.Design.VisualStudio.VsUtils.GetProviderServicesFromConfig(String invariantName, Project proect, IServiceProvider serviceProvider)
   at Microsoft.Data.Entity.Design.VisualStudio.VsUtils.GetModernProviderTypeNameFromProject(String invariantName, Project project, IServiceProvider serviceProvider)
   at Microsoft.Data.Entity.Design.VisualStudio.VsUtils.GetModernProviderTypeNameFromProject(String invariantName, Project project, IServiceProvider serviceProvider)
   at Microsoft.Data.Entity.Design.VisualStudio.VsUtils.IsModernProviderAvailable(String providerInvariantName, Project project, IServiceProvider serviceProvider)
   at Microsoft.Data.Entity.Design.VisualStudio.ModelWizard.Engine.DataConnectionUtils.HasModernEntityFrameworkProvider(IVsDataProviderManager dataProviderManager, Guid ......
&lt;truncated&gt;
```

---
#### Visual Studio Feedback System on 7/23/2019, 03:21 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Visual Studio Feedback System on 7/23/2019, 11:41 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Lawrence Jones [MSFT] on 7/25/2019, 03:30 PM: 

<p>That button is not specific to Entity Framework. That said, can you attach what was in your app.config or web.config file at the time?</p>

---
### Original Solutions
(no solutions)

**Comment by lajones** [comment]
According to [the docs](https://docs.microsoft.com/en-us/dotnet/api/system.configuration.configuration.getsection?view=netframework-4.8) `GetSection()` can return null if there is no such section. Need to update `AppConfigReader` to guard against this.
