### ISSUE TITLE
MissingManifestResourceException

### ISSUE THREAD

**Issue by Varorbc** [aspnet/EntityFramework6#1258]
```
Exception message:System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "ClassLibrary1.Migrations.Test.resources" was correctly embedded or linked into assembly "ClassLibrary1" at compile time, or that all the satellite assemblies required are loadable and fully signed.
Stack trace:
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at ClassLibrary1.Migrations.Test.System.Data.Entity.Migrations.Infrastructure.IMigrationMetadata.get_Target()
   at System.Data.Entity.Migrations.DbMigration.GetModel(Func`2 modelAccessor)
   at System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorScriptingDecorator.ScriptUpdate(String sourceMigration, String targetMigration)
   at System.Data.Entity.Infrastructure.Design.Executor.ScriptUpdate.<>c__DisplayClass0_0.<.ctor>b__0()
   at System.Data.Entity.Infrastructure.Design.Executor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at System.Data.Entity.Infrastructure.Design.Executor.OperationBase.Execute(Action action)
```

### Further technical details
EF version: 6.3.0-preview9-19423-04
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.2.4

**Comment by bricelam** [comment]
@Varorbc This is an issue with the SDK. I've filed https://github.com/dotnet/sdk/issues/3639.

### Workaround
You can work around the issue by adding this to your csproj:

``` xml
<PropertyGroup>
  <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
</PropertyGroup>
```

Unfortunately, in 3.0 Preview 9 you'll then hit https://github.com/microsoft/msbuild/issues/4695, but this should be fixed in the next release.

**Comment by bricelam** [comment]
@marchy said:
> The command doesn't seem to take the selected 'Default project' into account (nor the directory it is being issued from). So command is always running against wrong project.

![image](https://user-images.githubusercontent.com/1226749/64888613-46678e00-d620-11e9-9e84-3ff77c069ef9.png)

![image](https://user-images.githubusercontent.com/1226749/64888621-4b2c4200-d620-11e9-976f-bdba9c87a8d9.png)

**Comment by mjamro** [comment]
I'm targeting `net461` and the workaround with `EmbeddedResourceUseDependentUponConvention` is not working.

Instead i'm using:

```
<ItemGroup>
    <EmbeddedResource Update="**\*.resx">
        <DependentUpon>$([System.String]::Copy('%(FileName)')).cs</DependentUpon>
    </EmbeddedResource>
</ItemGroup>
```

which seems to work just fine.

**Comment by SylwesterZarebski** [comment]
[**@mjamro**](https://github.com/mjamro) commented on [Jul 23, 2021, 3:01 PM GMT+2](https://github.com/dotnet/ef6/issues/1258#issuecomment-885621398 "2021-07-23T13:01:19Z - Replied by Github Reply Comments"):
> I'm targeting `net461` and the workaround with setting `EmbeddedResourceUseDependentUponConvention` is not working.
> 
> Instead i'm using:
> 
> ```
> <ItemGroup>
>     <EmbeddedResource Update="**\*.resx">
>         <DependentUpon>$([System.String]::Copy('%(FileName)')).cs</DependentUpon>
>     </EmbeddedResource>
> </ItemGroup>
> ```
> 
> which seems to work just fine.

Both settings are required, `EmbeddedResourceUseDependentUponConvention` **AND** setting embeddedresource `.resx` to `DependentUpon` -> `.cs`.
