### ISSUE TITLE
CommitFailureTests are flakey/order-dependent

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework6#130]
I sometimes get errors like this when runnin all tests:

> Test 'System.Data.Entity.Interception.CommitFailureTests.BuildDatabaseInitializationScript_can_be_used_to_initialize_the_database' failed:
	Assert.Empty() failure
	TestHelpers\DbDispatchersHelpers.cs(24,0): at System.Data.Entity.TestHelpers.DbDispatchersHelpers.AssertNoInterceptors()
	Interception\CommitFailureTests.cs(857,0): at System.Data.Entity.Interception.CommitFailureTests.BuildDatabaseInitializationScript_can_be_used_to_initialize_the_database()

But then running the tests again on their own passes. This often indicates that there is an order-dependency. It seems likely that some other test is leaving an interceptor registered.

**Comment by ajcvickers** [comment]
Also: DatabaseLogFormatterTests.DatabaseLogFormatter_is_disposed_even_if_the_context_is_not
