### ISSUE TITLE
Ability to rely on cascade delete

### ISSUE THREAD

**Issue by jnm2** [aspnet/EntityFramework6#163]
I have a scenario where level 1 entities own level 2 entities, and so have a cascading delete relationship. Level 3 entities are related to level 2 but are owned by a fourth table outside this particular hierarchy, and so have a non-cascading relationship to level 2 entities.

In order to delete level 1 entities, my code also needs to delete level 3 entities manually and then perform further work on the fourth table. The level 2 entities should just be deleted because they are owned by level 1 entities and have the cascading delete.

What's irritating is that I can't rely on the level 2 cascade deletes. I have to manually load and remove each level 2 entity. Even though EF knows that deleting level 1 entities could mean deleting level 2 entities, and that level 2 entities can't be deleted until level 3 entities are deleted, it tries to do the level 1 delete before the level 3 delete.

I see why this happens. EF is not tracking any level 2 entities, and so it assumes that there can be no dependencies between the level 3 and level 1 deletes. This assumption would be solid if there was no cascading delete between 1 and 2, but as it is the assumption is faulty.

In an ideal world, the order of deletes should be calculated based on foreign key relationships. It should not change from one SaveChanges to another, regardless of what entities are being tracked. Even if I'm deleting two totally unrelated level 1 and 3 entities, the level 3 entity should still be deleted first. It should be up to me whether I want to set the state of level 2 entities or even track them in the context at all.

EF 6.1.3 sample:

```c#
private static DbConnection CreateConnection() => new SqlConnection(new SqlConnectionStringBuilder
{
    DataSource = ?,
    InitialCatalog = ?,
    IntegratedSecurity = ?
}.ToString());

public static void Main()
{
    using (var db = new TestContext(CreateConnection()))
    {
        db.Database.Delete();
        db.Database.Create();

        db.Level3Items.Add(new Level3Item
        {
            Level2Item = new Level2Item
            {
                Level1Item = new Level1Item()
            }
        });

        db.SaveChanges();
    }


    using (var db = new TestContext(CreateConnection()))
    {
        db.Level3Items.Remove(db.Level3Items.Single());

        // It would be awesome if I didn't have to load the level 2 entities but instead could rely on cascade delete
        // db.Level2Items.Remove(db.Level2Items.Single()); 

        db.Level1Items.Remove(db.Level1Items.Single());

        db.SaveChanges();
    }
}

public sealed class TestContext : DbContext
{
    public TestContext(DbConnection connection) : base(connection, true)
    {
    }

    public DbSet<Level1Item> Level1Items { get; set; }
    public DbSet<Level2Item> Level2Items { get; set; }
    public DbSet<Level3Item> Level3Items { get; set; }

    protected override void OnModelCreating(DbModelBuilder m)
    {
        m.Entity<Level2Item>().HasRequired(_ => _.Level1Item).WithMany().WillCascadeOnDelete();
        m.Entity<Level3Item>().HasRequired(_ => _.Level2Item).WithMany().WillCascadeOnDelete(false);
    }
}

public sealed class Level1Item
{
    public int Id { get; set; }
}

public sealed class Level2Item
{
    public int Id { get; set; }

    public int Level1ItemId { get; set; }
    public Level1Item Level1Item { get; set; }
}

public sealed class Level3Item
{
    public int Id { get; set; }

    public int Level2ItemId { get; set; }
    public Level2Item Level2Item { get; set; }
}
```

**Comment by rowanmiller** [comment]
We should re-discuss in triage as we misunderstood what was happening here, but I now get it 😄.

BTW this does also repro on EF Core...

```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Linq;

namespace Repro
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new TestContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                db.Level3Items.Add(new Level3Item
                {
                    Level2Item = new Level2Item
                    {
                        Level1Item = new Level1Item()
                    }
                });

                db.SaveChanges();
            }

            using (var db = new TestContext())
            {
                db.Level3Items.Remove(db.Level3Items.Single());
                db.Level1Items.Remove(db.Level1Items.Single());
                db.SaveChanges();
            }

        }
    }

    public sealed class TestContext : DbContext
    {
        public DbSet<Level1Item> Level1Items { get; set; }
        public DbSet<Level2Item> Level2Items { get; set; }
        public DbSet<Level3Item> Level3Items { get; set; }

        protected override void OnModelCreating(ModelBuilder m)
        {
            m.Entity<Level2Item>().HasOne(_ => _.Level1Item).WithMany().OnDelete(DeleteBehavior.Cascade);
            m.Entity<Level3Item>().HasOne(_ => _.Level2Item).WithMany().OnDelete(DeleteBehavior.Restrict);
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Repro.Cascade;Trusted_Connection=True;");
        }
    }

    public sealed class Level1Item
    {
        public int Id { get; set; }
    }

    public sealed class Level2Item
    {
        public int Id { get; set; }

        public int Level1ItemId { get; set; }
        public Level1Item Level1Item { get; set; }
    }

    public sealed class Level3Item
    {
        public int Id { get; set; }

        public int Level2ItemId { get; set; }
        public Level2Item Level2Item { get; set; }
    }
}
```

```
Microsoft.EntityFrameworkCore.DbUpdateException was unhandled
  HResult=-2146233088
  Message=An error occurred while updating the entries. See the inner exception for details.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
       at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
       at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
       at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
       at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, TState state)
       at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
       at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
       at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
       at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
       at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
       at ConsoleApplication4.Program.Main(String[] args) in C:\Users\rowmil\Documents\Visual Studio 2015\Projects\ConsoleApplication4\ConsoleApplication4\Program.cs:line 37
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       Class=16
       ErrorCode=-2146232060
       HResult=-2146232060
       LineNumber=2
       Message=The DELETE statement conflicted with the REFERENCE constraint "FK_Level3Items_Level2Items_Level2ItemId". The conflict occurred in database "Repro.Cascade", table "dbo.Level3Items", column 'Level2ItemId'.
The statement has been terminated.
       Number=547
       Procedure=""
       Server=(localdb)\mssqllocaldb
       Source=.Net SqlClient Data Provider
       State=0
       StackTrace:
            at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
            at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
            at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
            at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
            at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
            at System.Data.SqlClient.SqlDataReader.get_MetaData()
            at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
            at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
            at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
            at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
            at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
            at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
            at System.Data.Common.DbCommand.ExecuteReader()
            at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
            at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
            at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
       InnerException: 
```

**Comment by rowanmiller** [comment]
Discussed at length and decided not to try and fix this. At the moment we do a topological sort based on data and addressing this would mean we need to also sort based on the model. We could look at doing this in EF Core if we see more folks hitting this, but given we haven't seen a lot of reports on EF6.x (and the behavior has been around since 2008), it seems like it is probably not a very common issue. Given the cost, complexity, and potential performance impact, we aren't going to do it now.

**Comment by jnm2** [comment]
> Given the cost, complexity, and potential performance impact, we aren't going to do it now.

A topological sort based on the model would be a potential performance boost because it can be calculated once per model rather than once per SaveChanges. Not to mention that this is arguably an actual correctness issue, i.e. a bug. Would you at least be willing to consider a community contribution down the road?

**Comment by rowanmiller** [comment]
We'd still have to do a topological sort by data as well, because there are very common patterns where a model-based sort couldn't give a definitive answer on the correct order to do things... but a data-based sort would give a better result.

We would consider a PR.

**Comment by jnm2** [comment]
> We'd still have to do a topological sort by data as well, because there are very common patterns where a model-based sort couldn't give a definitive answer on the correct order to do things... but a data-based sort would give a better result.

True- a self-referential table, for example. Thanks for that.

> We would consider a PR.

I'll put this on my bucket list of things to improve then. The up-for-grabs tag might be nice because who knows- maybe someone else will get there first.
