### ISSUE TITLE
CommitFailureHandler not working correctly with database first connection strings

### ISSUE THREAD

**Issue by sishik1** [aspnet/EntityFramework6#256]
I created a test project using VS 2012 with EF 6.1.3 to test CommitFailureHandler with code-first and database-first (EDMX). If I use code first with CommitFailureHandler, everything works as corrected. When I switch to use database-first connection string **and** connection string uses SQL user authentication (non-windows), I get the following exception:

```
System.Data.Entity.Utilities.DbProviderServicesExtensions.GetProviderManifestTokenChecked(DbProviderServices providerServices, DbConnection connection)
            InnerException: System.InvalidOperationException
                 HResult=-2146233079
                 Message=This operation requires a connection to the 'master' database. Unable to create a connection to the 'master' database because the original database connection has been opened and credentials have been removed from the connection string. Supply an unopened connection.
                 Source=EntityFramework.SqlServer
                 StackTrace:
                      at System.Data.Entity.SqlServer.SqlProviderServices.UsingMasterConnection(DbConnection sqlConnection, Action`1 act)
                      at System.Data.Entity.SqlServer.SqlProviderServices.GetDbProviderManifestToken(DbConnection connection)
                      at System.Data.Entity.Core.Common.DbProviderServices.GetProviderManifestToken(DbConnection connection)
                 InnerException: System.Data.SqlClient.SqlException
                      HResult=-2146232060
                      Message=Login failed for user 'xxxx'.
                      Source=.Net SqlClient Data Provider
                      ErrorCode=-2146232060
                      Class=14
                      LineNumber=65536
                      Number=18456
                      Procedure=""
                      Server=someserver
                      State=1
                      StackTrace:
                           at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
                           at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
                           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
                           at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
                           at System.Data.SqlClient.SqlConnection.Open()
                           at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<Open>b__38(DbConnection t, DbConnectionInterceptionContext c)
                           at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
                           at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
                           at System.Data.Entity.SqlServer.SqlProviderServices.<>c__DisplayClass31.<UsingConnection>b__2f()
                           at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
                           at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
                           at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
                           at System.Data.Entity.SqlServer.SqlProviderServices.UsingConnection(DbConnection sqlConnection, Action`1 act)
                           at System.Data.Entity.SqlServer.SqlProviderServices.UsingMasterConnection(DbConnection sqlConnection, Action`1 act)
                      InnerException: 
```
Here are the connection strings I'm using (code-first one works)
```xml
  <connectionStrings>
    <add name="Test_CodeFirst" providerName="System.Data.SqlClient" connectionString="data source=someserver;initial catalog=MainDB;user id=someuser;password='xxxx';MultipleActiveResultSets=True;App=EntityFramework;Trusted_Connection=False;" />
    <add name="Test_DbFirst" connectionString="metadata=res://*/TestModel.csdl|res://*/TestModel.ssdl|res://*/TestModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=someserver;initial catalog=MainDB;user id=someuser;password='xxxx';MultipleActiveResultSets=True;App=EntityFramework;Trusted_Connection=False;&quot;" providerName="System.Data.EntityClient" />
  </connectionStrings>
```

Here is some code

```C#
public static class Program
    {
        private static int Main(string[] args)
        {
           //   CodeFirst_Test();
            DatabaseFirst_Test();
            return 1;
        }

        private static void CodeFirst_Test()
        {
            using (UserInfoContext context = new UserInfoContext())
            {
                UserInfo u = new UserInfo();
                u.UserName = "test 1";
                u.Address1 = "some address";

                context.Users.Add(u);
                context.SaveChanges();
            }
        }

        private static void DatabaseFirst_Test()
        {
            using (TestContext context = new TestContext())
            {
                User u = new User();
                u.UserName = "test 1";
                u.Address1 = "some address";

                context.Users.Add(u);
                context.SaveChanges();
            }
        }
    }

[Serializable]
    internal class UserInfo
    {
        public int UserId { get; set; }

        public string UserName { get; set; }

        public string Address1 { get; set; }
    }

internal class UserInfoMap : EntityTypeConfiguration<UserInfo>
    {
        public UserInfoMap()
        {
            this.HasKey(t => t.UserId);

            this.Property(t => t.UserId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            this.Property(t => t.UserName).HasMaxLength(50);
            this.Property(t => t.Address1).HasMaxLength(50);

            this.ToTable("Users");
        }
    }

internal class UserInfoContext : BaseMainContext<UserInfoContext>
    {
        public DbSet<UserInfo> Users { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            if (modelBuilder == null)
            {
                throw new ArgumentNullException("modelBuilder");
            }

            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new UserInfoMap());
        }
    }

[DbConfigurationType(typeof(DbContextConfiguration))]
    internal abstract class BaseMainContext<TContext> : DbContext where TContext : DbContext
    {
        static BaseMainContext()
        {
            Database.SetInitializer<TContext>(null);
            Database.SetInitializer<TransactionContext>(null);
        }

        protected BaseMainContext()
            : base("Name=Test_CodeFirst")
        {
            this.Configuration.ProxyCreationEnabled = false;
            this.Configuration.LazyLoadingEnabled = false;
        }
    }

public class DbContextConfiguration : DbConfiguration
    {
        public DbContextConfiguration()
        {
            this.SetProviderServices(SqlProviderServices.ProviderInvariantName, SqlProviderServices.Instance);

            //if (ConfigurationServices.GetSetting("customExecutionStrategy", false))
            {
              //  this.SetExecutionStrategy(SqlProviderServices.ProviderInvariantName, () => new SqlAzureExecutionStrategy());
            }

            this.SetTransactionHandler(SqlProviderServices.ProviderInvariantName, () => new CommitFailureHandler());
        }
    }

```

For database-first, I just created EDMX file that uses Test_DbFirst connection string and imported 'Users' table.

Thanks!

**Comment by ajcvickers** [comment]
@sishik1 You can [add '`Persist Security Info = True`' to your connection string](https://stackoverflow.com/questions/19977141/this-operation-requires-a-connection-to-the-master-database) to prevent credentials been stripped out when opening the connection, or call `DbConfiguration.SetManifestTokenResolver` so that EF can know the database version without connecting to the master database.
