### ISSUE TITLE
Migrations not working due to not being able to load assembly

### ISSUE THREAD

**Issue by RealDotNetDave** [aspnet/EntityFramework6#292]
If I try to Enable or Add Migrations in my solution I get the error below. I re-created both the models project and DB context project and it still happens. 

Checking if the context targets an existing database...
System.IO.FileNotFoundException: Could not load file or assembly 'GallusGolf.Api.DataModels, Version=2017.5.26.16197, Culture=en-US, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'GallusGolf.Api.DataModels, Version=2017.5.26.16197, Culture=en-US, PublicKeyToken=null'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParametersNoCopy()
   at System.Reflection.RuntimePropertyInfo.GetIndexParametersNoCopy()
   at System.Reflection.RuntimePropertyInfo.GetIndexParameters()
   at System.Data.Entity.Internal.DbSetDiscoveryService.<GetSets>b__0(PropertyInfo p)
   at System.Linq.Enumerable.<>c__DisplayClass6_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
   at System.Data.Entity.Internal.DbSetDiscoveryService.GetSets()
   at System.Data.Entity.Internal.DbSetDiscoveryService.InitializeSets()
   at System.Data.Entity.DbContext.InitializeLazyInternalContext(IInternalConnection internalConnection, DbCompiledModel model)
   at System.Data.Entity.DbContext..ctor(String nameOrConnectionString)
   at GallusGolf.Api.DataAccess.GolfApiDbContext..ctor() in C:\Users\David\Source\Repos\Gallus.Api\src\GallusGolf.Api.DataAccess\GolfApiDbContext.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Data.Entity.Infrastructure.DbContextInfo.CreateInstance()
   at System.Data.Entity.Infrastructure.DbContextInfo..ctor(Type contextType, DbProviderInfo modelProviderInfo, AppConfig config, DbConnectionInfo connectionInfo, Func`1 resolver)
   at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration, DbContext usersContext, DatabaseExistenceState existenceState, Boolean calledByCreateDatabase)
   at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration)
   at System.Data.Entity.Migrations.Design.MigrationScaffolder..ctor(DbMigrationsConfiguration migrationsConfiguration)
   at System.Data.Entity.Migrations.Design.ToolingFacade.ScaffoldRunner.Run()
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.ScaffoldInitialCreate(String language, String rootNamespace)
   at System.Data.Entity.Migrations.EnableMigrationsCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)

Could not load file or assembly 'GallusGolf.Api.DataModels, Version=2017.5.26.16197, Culture=en-US, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

**Comment by RealDotNetDave** [comment]
I figured out the issue. If I remove the [assembly: AssemblyCulture("en-US")] attribute from my models project then everything works fine. This must be a bug in EF.

**Comment by ajcvickers** [comment]
On reading the [documentation for AssemblyCulture](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assemblycultureattribute?view=netframework-4.7.2) I believe this is by-design. Specifically, "Labeling a traditional code library with this attribute will break it, because no other code will be able to find the library's entry points at runtime."
