### ISSUE TITLE
Postfix entity name when using the DB First designer

### ISSUE THREAD

**Issue by QuantumHive** [aspnet/EntityFramework6#318]
Is it possible to postfix Entity class names when using the DB First Designer approach in `EF 6.1.x`?
For example if I have a database table called `Person`, that whenever I do `Update model from Database...`, it could generate the following class?

`public partial class PersonEntity { ... }`

where Entity Framework postfixed the class name with `-Entity`.

I tried to modify the `.tt` files where it would generate the classes like this, but at runtime I got the following error:

> System.InvalidOperationException: 'The entity type 'PersonEntity' is not part of the model for the current context.'

with the following stacktrace:
```
   at System.Data.Entity.Internal.InternalContext.UpdateEntitySetMappingsForType(Type entityType)
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Select[TSource,TResult](IQueryable`1 source, Expression`1 selector)
```

I know I could manually edit the Entity Type name in the designer, but when going DB First approach, and having a lot of tables, it would be nice if this could be done by the tooling.

The reason I want this is because I don't want the types in my DataAccess Layer to have the same name as the model types defined in my Domain or Business Layer.

**Comment by ajcvickers** [comment]
Discussed this in triage and the most practical solution we can come up with is to post-process the EDMX file after it is generated.

**Comment by QuantumHive** [comment]
Okay, so it's a missing feature. I wouldn't really call it practical for every scenario.
