### ISSUE TITLE
Adding Multi-column UNIQUE CONSTRAINT including a Column with a FK CONSTRAINT generates erroneous Migration Step on MySQL

### ISSUE THREAD

**Issue by EdouardMYOB** [aspnet/EntityFramework6#518]
## Problem 

When I have a table with a FK CONSTRAINT, and then add a new Multi-column CONSTRAINT that includes the index covered in the FK, `Add-Migration` creates a new DbMigration step that throws an error:

```
PM> Update-Database -ProjectName DevOps.Data -StartUpProjectName DevOps.Data -ConfigurationTypeName DevOps.Data.Db.Migrations.Configuration -ConnectionStringName DbContext -Verbose
Using StartUp project 'DevOps.Data'.
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Target database is: 'DB' (DataSource: 192.168.82.1, Provider: MySql.Data.MySqlClient, Origin: Explicit).
Applying explicit migrations: [201804082355119_AddUniqueSiteTagsConstraint].
Applying explicit migration: 201804082355119_AddUniqueSiteTagsConstraint.
alter table `SiteTag` drop index `IX_SiteId`
System.Runtime.Serialization.SerializationException: Type is not resolved for member 'MySql.Data.MySqlClient.MySqlException,MySql.Data, Version=6.9.8.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d'.
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Update(String targetMigration, Boolean force)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Type is not resolved for member 'MySql.Data.MySqlClient.MySqlException,MySql.Data, Version=6.9.8.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d'.
```

## Background

I'm working with a database that has a Sites table (PK is Sites.SiteID).

Later on a SiteTags table was added, and the following DbMigration was created:

```c#
        public override void Up()
        {
            CreateTable(
                "dbo.SiteTag",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        SiteId = c.Guid(nullable: false),
                        Key = c.String(maxLength: 100, storeType: "nvarchar"),
                        Value = c.String(maxLength: 100, storeType: "nvarchar"),
                    })
                .PrimaryKey(t => t.Id)
                .ForeignKey("dbo.Site", t => t.SiteId, cascadeDelete: true, name: "FK_SiteTag_Site_SiteId")
                .Index(t => t.SiteId);
        }
```

The problem arose when I then added a new Multi-column UNIQUE CONSTRAINT on SiteId/Key/Value (marking the additions with `/**/`):

```c#
    [DataContract(IsReference=true)]
    [Serializable]
    public class SiteTag : EntityBaseClass
    {
        [Key]
        [DataMember]
        public int Id { get; set; }
        
        [Required]
        [DataMember]
/**/    [Index("SiteTag_Unique_SiteId_Key_Value", 1, IsUnique = true)]
        public Guid SiteId { get; set; }

        [StringLength(100, ErrorMessage = "Key cannot be longer than 100 characters.")]
        [Display(Name = "Key")]
        [DataMember]
/**/    [Index("SiteTag_Unique_SiteId_Key_Value", 2, IsUnique = true)]
        public string Key { get; set; }

        [StringLength(100, ErrorMessage = "Value cannot be longer than 100 characters.")]
        [Display(Name = "Value")]
        [DataMember]
/**/    [Index("SiteTag_Unique_SiteId_Key_Value", 3, IsUnique = true)]
        public string Value { get; set; }

        [DataMember]
        public virtual Site Site { get; set; }
    }
```

Running `Add-Migration` results in the following DbMigration:

```c#
    public partial class AddUniqueSiteTagsConstraint : DbMigration
    {
        public override void Up()
        {
            DropIndex("dbo.SiteTag", new[] { "SiteId" });
            CreateIndex("dbo.SiteTag", new[] { "SiteId", "Key", "Value" }, unique: true, name: "SiteTag_Unique_SiteId_Key_Value");
        }

        public override void Down()
        {
            DropIndex("dbo.SiteTag", "SiteTag_Unique_SiteId_Key_Value");
            CreateIndex("dbo.SiteTag", "SiteId");
        }
    }
```

Running `Update-Database` gives an error (see the exception at the top of the report). Manually running the ALTER statement on my MySQL instance tells me the error is:

```
12:15:29	alter table DB.SiteTag drop index `IX_SiteId`	Error Code: 1553. Cannot drop index 'IX_SiteId': needed in a foreign key constraint	0.0091 sec
```

## Error Analysis

I believe that the problem is `Add-Migration` has decided that it can remove the original index because the Multi-column index also covers SiteId (as SiteId is the first element in the compound index). But the order in which it generates the statements (remove the original index, create the compound index) fails because that violates the FK constraint. 

If I manually reverse the order of the statements in the DbMigration (create the compound index, remove the original index) then everything succeeds. This makes sense to me as there is no point at which there is no index covering SiteId that is required by the FK constraint.

## Expected Resolution

`Add-Migration` generates the statements in the reverse order of it's current implementation (create the compound index first, then remove the original index)

**Comment by EdouardMYOB** [comment]
The order of the statements in the Down() method also need to be reversed in order for Downgrades to succeed.

**Comment by ajcvickers** [comment]
@EdouardMYOB Looks like this is an issue with the MySQL provider. Can you please follow up with them.
