### ISSUE TITLE
.NET 4.7.2 (and Windows 10 1803) upgrade - Entity Framework v6.2.0 timeout exception

### ISSUE THREAD

**Issue by rossmhk** [aspnet/EntityFramework6#538]
After upgrading to .NET 4.7.2, a number of Entity Framework queries are now failing against Azure SQL DB.  This is confirmed to be not happening on .NET 4.7.1.

```
System.Data.SqlClient.SqlException: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: The wait operation timed out
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.<ExecuteStoreCommandsAsync>d__c.MoveNext()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.<ExecuteStoreCommandsAsync>d__c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.<ExecuteAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

### Steps to reproduce
Seems to be a pattern where there a 3 of more tables involved and the EF LINQ expression has an Include statement.  For example, one of the simpler examples:

```
string username = "john";
var user = _context.Users.Include("User_UserRoles.UserRole").Where(u => u.UserName == username).FirstOrDefault();
```

### Further technical details
EF version: v6.20
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10 1803 / .NET 4.7.2
IDE: Visual Studio 2017 15.7 / 15.8.0 (Preview 1.1)

**Comment by divega** [comment]
@rossmhk Thanks a lot of reporting this. I am going to be moving this issue to a different repository, where issues for SqlClient on .NET Framework are tracked. 

Once there, it would be great if you could provide a repro project for the SqlClient team to investigate.

**Comment by divega** [comment]
This issue was moved to Microsoft/dotnet#750
