### ISSUE TITLE
Default constraint isn't being dropped before altering column which causes an error

### ISSUE THREAD

**Issue by xt0rted** [aspnet/EntityFramework6#54]
One of my enums was created using `byte` and now I'm trying to switch it to `int`. I'm getting an error because the default constraint added for this column isn't being dropped before altering the column. I believe this is the same issue as https://github.com/aspnet/EntityFramework/issues/1345

The results of running the migration are

```
Applying explicit migration: 201608250548579_update enum data type to int.
ALTER TABLE [dbo].[AgencyAgreements] ALTER COLUMN [Status] [int] NOT NULL
ALTER TABLE [dbo].[Transactions] ALTER COLUMN [BillOfSale_Status] [int] NOT NULL
System.Data.SqlClient.SqlException (0x80131904): The object 'DF__Transacti__BillO__4E88ABD4' is dependent on column 'BillOfSale_Status'.
ALTER TABLE ALTER COLUMN BillOfSale_Status failed because one or more objects access this column.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<NonQuery>b__0(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   at System.Data.Entity.Migrations.DbMigrator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinTransaction(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinNewTransaction(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClass30.<ExecuteStatements>b__2e()
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.Execute(Action operation)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.ExecuteStatements(IEnumerable`1 migrationStatements)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
   at System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClassc.<Update>b__b()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorBase.Update(String targetMigration)
   at System.Data.Entity.Migrations.Design.ToolingFacade.UpdateRunner.Run()
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.AppDomain.DoCallBack(CrossAppDomainDelegate callBackDelegate)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Run(BaseRunner runner)
   at System.Data.Entity.Migrations.Design.ToolingFacade.Update(String targetMigration, Boolean force)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2.<.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
ClientConnectionId:5befeded-6fb9-427c-aa92-84698dbfe816
Error Number:5074,State:1,Class:16
The object 'DF__Transacti__BillO__4E88ABD4' is dependent on column 'BillOfSale_Status'.
ALTER TABLE ALTER COLUMN BillOfSale_Status failed because one or more objects access this column.
```

**Comment by ErikEJ** [comment]
This repo is for EF6 - is this an EF6 issue?

**Comment by xt0rted** [comment]
Yea, I'm using version 6.1.3

**Comment by xt0rted** [comment]
I just stepped through my migrations to see where the default constrains were coming from (there's two, while other similar columns don't have any). It seems there's a different end result between using `CreateTable()` and `AddColumn()`.

This results in the column being created without a default value.
```c#
CreateTable(
    "dbo.AgencyAgreements",
    c => new
        {
            Id = c.Int(nullable: false, identity: true),
...
            Status = c.Byte(nullable: false),
        })
    .PrimaryKey(t => t.Id);
```

```sql
CREATE TABLE [dbo].[AgencyAgreements] (
    [Id] [int] NOT NULL IDENTITY,
...
    [Status] [tinyint] NOT NULL,
    CONSTRAINT [PK_dbo.AgencyAgreements] PRIMARY KEY ([Id])
)
```

This results in the column being created with a default value.
```c#
AddColumn("dbo.Transactions", "BillOfSale_Status", c => c.Byte(nullable: false));
```
```sql
ALTER TABLE [dbo].[Transactions] ADD [BillOfSale_Status] [tinyint] NOT NULL DEFAULT 0
```

Changing the type from `byte` to `int` only causes an issue on the columns that were created using `AddColumn()` while those created with `CreateTable()` are fine.

**Comment by bricelam** [comment]
When adding `NOT NULL` columns, we synthesize a default value for any existing rows. It looks like our logic to [drop default constraints](https://github.com/aspnet/EntityFramework6/blob/3207eb9347c2cfe706304b27c6e788a2843bbbec/src/EntityFramework.SqlServer/SqlServerMigrationSqlGenerator.cs#L773-L777) before `ALTER COLUMN` doesn't take this into account.

**Comment by bricelam** [comment]
EF Core does not have this bug because we *always* try to drop default constraints before altering columns.

**Comment by xt0rted** [comment]
Since I don't need default values on these columns (I'm setting both on initial insert) I [added this](http://stackoverflow.com/a/13275441/39605) to my migration to drop the constraints all together for now.
