### ISSUE TITLE
Translation of sum does not match local execution for nullable values

### ISSUE THREAD

**Issue by evilhappy333** [aspnet/EntityFramework6#548]
Describe what is not working as expected.

When you execute sum on an empty set of non-nullable numerical types, null is returned instead of 0. If you attempt to materialize this null value as the non-nullable type an exception is thrown.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:  Unhandled Exception: System.InvalidOperationException: The cast to value type 'System.Decimal' failed because the materialized value is null. Either the result type's generic parameter or the query must use a nullable type.
Stack trace:  at System.Data.Entity.Core.Common.Internal.Materialization.Shaper.ErrorHandlingValueReader`1.GetValue(DbDataReader reader, Int32 ordinal)
   at lambda_method(Closure , Shaper )
   at System.Data.Entity.Core.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__3[TResult](IEnumerable`1 sequence)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Sum[TSource](IQueryable`1 source, Expression`1 selector)
   at Test.Program.Main(String[] args) in D:\Projects\TotusGit\Test\Test\Program.cs:line 61
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#

public class TestEntity
{
	public virtual int Id { get; set; }

	public virtual decimal Number { get; set; }

}

class Program
{
	static void Main(string[] args)
	{
		Database.SetInitializer(new MigrateDatabaseToLatestVersion<TestContext, Migrations.Configuration>());

		using (var context = new TestContext())
		{
			context.Database.Delete();
			context.Database.Initialize(true);

			// Populate table
			{
				var testEntity = context.testEntities.Create();
				testEntity.Number = 1m;

				context.testEntities.Add(testEntity);
				context.SaveChanges();
			}

			// Verify summing works locally
			{
				// Empty array
				var testEntities = Enumerable.Empty<TestEntity>();

				var sum = testEntities.Sum(te => te.Number);

				// Expected:    Test1: 0
				// Actual:      Test1: 0
				Console.WriteLine($"Test1: {sum}");
			}


			// Summing can return incorrect results in some cases
			{
				// Throws exception
				var summedValue = context.testEntities
					.Sum(te => 
						(decimal?) (
							te.Number + 
							context.testEntities
								.Where(te2 => false)
								.Sum(te2 => te2.Number)));

				// Expected:    Test2: 1
				// Actual:      Test2: 9999
				Console.WriteLine($"Test2: {summedValue.GetValueOrDefault(9999)}");
			}

			// Code should not work
			{
				// Throws exception
				var summedValue = context.testEntities
					.Where(te => false)
					.Sum(te => te.Number);
				
				// Expected:    Test3: 0
				// Actual:      (Exception thrown)
				Console.WriteLine($"Test3: {summedValue}");
			}
		}
	}
}
```

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.7.2

### Work-around

Constructing a query such as below results in the expected behavior.
```c#
var summedValue = context.testEntities
	.Sum(te => 
		(decimal?) (
			te.Number + 
			context.testEntities
				.Where(te2 => false)
				.Sum(te2 => (decimal?) te2.Number) ?? 0m ));

var summedValue = context.testEntities
	.Where(te => false)
	.Sum(te => (decimal?) te.Number) ?? 0m;
                    
```

**Comment by HappyRashair** [comment]
It works in `6.1.3` version.
See also: https://github.com/dotnet/ef6/issues/439#issuecomment-1168605199
