### ISSUE TITLE
Entity Framework should not throw NullReferenceException

### ISSUE THREAD

**Issue by jnm2** [aspnet/EntityFramework6#588]
Entity Framework should show an explanatory exception message rather than throwing NRE from its own code.

I'm going to have to split the actual table into two rather than this manual TPH construction because Entity Framework can't use a unique constraint in place of a primary key, but it'll make directly working with the table much more confusing.

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=mscorlib
  StackTrace:
   at System.Object.GetType()
   at System.Data.Entity.Core.EntityKey.ValidateTypeOfKeyValue(MetadataWorkspace workspace, EdmMember keyMember, Object keyValue, Boolean isArgumentException, String argumentName)
   at System.Data.Entity.Core.EntityKey.ValidateEntityKey(MetadataWorkspace workspace, EntitySet entitySet, Boolean isArgumentException, String argumentName)
   at System.Data.Entity.Core.Objects.ObjectStateManager.CheckKeyMatchesEntity(IEntityWrapper wrappedEntity, EntityKey entityKey, EntitySet entitySetForType, Boolean forAttach)
   at System.Data.Entity.Core.Objects.ObjectStateManager.AddEntry(IEntityWrapper wrappedObject, EntityKey passedKey, EntitySet entitySet, String argumentName, Boolean isAdded)
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper.HandleEntityAppendOnly[TEntity](Func`2 constructEntityDelegate, EntityKey entityKey, EntitySet entitySet)
   at System.Data.Entity.Core.Common.Internal.Materialization.Coordinator`1.ReadNextElement(Shaper shaper)
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.SimpleEnumerator.MoveNext()
   at System.Data.Entity.QueryableExtensions.Load(IQueryable source)
   at Program.Main() in C:\Users\jmusser\Source\Repos\EF6 repro\EF6 repro\Program.cs:line 40
```

### Steps to reproduce

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace></RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.2.0" />
  </ItemGroup>

</Project>
```

```c#
using System.Data.Entity;
using System.Data.SqlClient;

public sealed class Program
{
    public static void Main()
    {
        using (var connection = new SqlConnection("Data Source=(local);Integrated Security=true"))
        {
            connection.Open();

            using (var command = new SqlCommand(@"
                if db_id('EF6_repro') is not null drop database EF6_repro;
                create database EF6_repro;",
                connection))
            {
                command.ExecuteNonQuery();
            }

            using (var command = new SqlCommand(@"
                use EF6_repro;

                create table dbo.TestEntities
                (
                    A int not null,
                    B int,
                    -- Can’t create a primary key across a nullable column
                    constraint UQ_TestEntities unique (A, B)
                );

                insert dbo.TestEntities values (1, null);",
                connection))
            {
                command.ExecuteNonQuery();
            }
        }

        using (var db = new TestDbContext())
        {
            db.TestEntities.Load();
        }
    }
}

public sealed class TestDbContext : DbContext
{
    public TestDbContext() : base("Data Source=(local);Initial Catalog=EF6_repro;Integrated Security=true")
    {
    }

    public DbSet<TestEntity> TestEntities { get; set; }

    protected override void OnModelCreating(DbModelBuilder b)
    {
        // Entity Framework needs us to define a primary key
        b.Entity<TestEntity>().HasKey(k => new { k.A, k.B });
    }
}

public sealed class TestEntity
{
    public int A { get; set; }
    public int? B { get; set; }
}
```

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8 Preview 5

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
