### ISSUE TITLE
ExecuteStoreQueryAsync fails with System.ArgumentException

### ISSUE THREAD

**Issue by divega** [aspnet/EntityFramework6#59]
_From @micktion on September 9, 2016 8:23_

I'm not sure if you're taking 6.1.3 issues or if this is an issue in EF 7.  I'll detail what I found as per your template...

### Steps to reproduce
Pass MergeOption in place of ExecutionOptions

### The issue
Fails with System.ArgumentException: No mapping exists from object type System.Data.IDataParameter[] to a known managed provider native type.

Exception message: System.ArgumentException: No mapping exists from object type System.Data.IDataParameter[] to a known managed provider native type.

Stack trace:
at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__167_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteStoreQueryInternalAsync>d__6f`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteInTransactionAsync>d__3d`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<ExecuteAsyncImplementation>d__9`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Data.Entity.Utilities.TaskExtensions.CultureAwaiter`1.GetResult()
   at System.Data.Entity.Core.Objects.ObjectContext.<ExecuteStoreQueryReliablyAsync>d__6c`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Tonic.Oms.Api.Tests.CoreTests.<TestStoreQueryAsync>d__25.MoveNext() in E:\Projects\oms-platform\Tonic.Oms.Api\Tonic.Oms.Api.Tests\CoreTests.cs:line 432
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

### Further technical details
The code that reproduces this issue is...

```
IDataParameter[] parameters = new IDataParameter[] {
	repository.CreateStoreQueryParameter("@LogonId", logonId),
	repository.CreateStoreQueryParameter("@Password", password),
	repository.CreateStoreQueryParameter("@status", status)};

var list = await repository.ModelObjectContext.ExecuteStoreQueryAsync<UserPasswordEntity>(
			commandText,
			MergeOption.AppendOnly,
			parameters);

```
Now it took me an afternoon to notice as this code compiles, runs then fails with a run time error, but the 2nd parameter should actually be of type ExecutionOptions and not a MergeOption enum. I don't know how this compiles, but it does, I'm guessing somewhere out there is an explicit cast operator from MergeOption to ExecutionOptions.

So when you pass ExecutionOptions it executes successfully...

```
ExecutionOptions options = new ExecutionOptions(MergeOption.AppendOnly);

IDataParameter[] parameters = new IDataParameter[] {
	repository.CreateStoreQueryParameter("@LogonId", logonId),
	repository.CreateStoreQueryParameter("@Password", password),
	repository.CreateStoreQueryParameter("@status", status)};

var list = await repository.ModelObjectContext.ExecuteStoreQueryAsync<UserPasswordEntity>(
			commandText,
			options,
			parameters);

```
I came across this error converting synchronous code to async.  There is a synchronous method which takes MergeOption as a parameter.
 
EF version: 6.1.3
Operating system: Windows 10
Visual Studio version: VS 2015

Other details about my project setup:

_Copied from original issue: aspnet/EntityFramework#6503_

**Comment by rowanmiller** [comment]
This overload resolution in the compiler. When you pass the `MergeOption` parameter it resolves to the `ExecuteStoreQueryAsync(string, params object[])` overload, meaning that `MergeOption.AppendOnly` and `parameters` are treated as parameters (hence the error about not being able to convert the parameter array to a parameter). When you supply the `ExecutionOptions` instead, it resolves to the `ExecuteStoreQueryAsync(string, ExecutionOptions, object[])` that you want.

This is just a side effect of how overload resolution and `params` works. Arguably this is poor API design on our part, but it's not something we would change at this stage.

**Comment by micktion** [comment]
When you're converting sync to async, you get use to just prefixing await and appending 'Async' to the method name and expect it'll perform the same function the equivalent synchronous method did.  

It was the inconsistency between the synchronous and asynchronous methods that caught me out.  Perhaps I'm slow, but it took a number of hours for me to realise the Syncrhonous method I was using didn't have an asynchronous method with the same signature.  It's not something you're use to seeing in an API.

I doubt I'll be the last person who loses a few hours to this one.

**Comment by divega** [comment]
@micktion Thanks for your bug report and sorry to hear you had to spend many hours figuring it out. You may not be the last one to hit this issue but this is the first report I remember on this. Hopefully customers that hit it in the future will search for the exception message and find this issue. 

I agree that you ran into this because the async overloads we added are inconsistent with the sync overloads. If there was an async overload that took a MergeOption argument overload resolution would prefer it to the params one. 

To give you some more context, by the time we added the async overloads of this method we had already considered the ObjectContext API to be legacy for some time and we didn't pay as much attention to consistency as to just exposing the raw functionality (because API is a building block for the more polished `SqlQuery()` methods in the DbContext API). I believe we would consider a well written PR that adds an overload and restores consistency between sync and async overloads, we just don't think this is high enough priority to tackle it.

**Comment by micktion** [comment]
OK so the API I'm using is semi-deprecated.

 I'll turn this into a suggestion.

I think there are a lot of people who are probably in my position, i.e. they have a large brown field project that they simply can't migrate to .NET Core in the near term, but are looking to make incremental changes that will help them gradually replace code not supported in .NET core with code that is.  

These people are probably hoping the quality of the EF6 framework would be maintained, for as long as it takes for them to move to EF7 and .NET Core.

I'm presuming filling a list of entities from a Stored Proc is something that is or will be supported in EF7. Is it something like... 

`IList<TEntity> entitiesFrom = Context.Set<TEntity>().FromSql("dbo.GetMyEntities @p = {0}", aParameter)`

...?

I think for functionality that is currently supported by the ObjectContext in EF6 that is supported in EF7 through other means, it would be useful to expose that same API in EF6 (even if it simply wraps the existing ObjectContext functionality) and then deprecate the methods on the ObjectContext.
