### ISSUE TITLE
EF cannot SaveChanges to SQL Server running inside Docker container

### ISSUE THREAD

**Issue by nojaf** [aspnet/EntityFramework6#596]
I running a WCF Service on Windows 10 and I'm trying to connect to a database running inside a Windows Container in Docker.

I'm able to connect to the database using DataGrip and ADO but anything EF related can't get through.
```
Exception message:
System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. 
Stack trace:
System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<NonQuery>b__0(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteNonQuery()
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
ClientConnectionId:561bcd0c-3d0c-4167-ac99-4b5ac21b1b2c
Error Number:-2,State:0,Class:11
```

### Steps to reproduce

```powershell
ps>docker run -n my-app -d -p 1433:1433 -e sa_password=MyStrongPW789 -e ACCEPT_EULA=Y microsoft/mssql-server-windows-developer:2017-latest
```
I've connect to the master DB and create my database manually.

```sql
CREATE DATABASE MyDb;
USE MyDb;
CREATE TABLE [dbo].[MyTable] (
  [Id] [int] NOT NULL,
  CONSTRAINT [PK_dbo.MyTable] PRIMARY KEY ([Id])
)
```

```c#
        try
            {
                using (SqlConnection conn =
                    new SqlConnection(ConfigurationManager.ConnectionStrings["MyDb"].ConnectionString))
                {
                    conn.Open();
                    var cmd = conn.CreateCommand();
                    cmd.CommandText = "SELECT 7;";
                    var reader = cmd.ExecuteReader();
                    reader.Read();
                    var value = reader[0];
                    conn.Close();
                }
                
                using (var ctx = new MyContext())
                {
                    new Configuration().SeedData(ctx);
                    ctx.SaveChanges();
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
```

Using SqlConnection I'm able to read the database. EF

### Further technical details
EF version: (found in project.csproj or packages.config): 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10 
Docker image: microsoft/mssql-server-windows-developer:2017-latest

**Comment by nojaf** [comment]
Yes, I'v double-checked that. Exactly the same connection string.

**Comment by ajcvickers** [comment]
@nojaf I haven't been able to reproduce this. Can you post a runnable project/solution or complete code listing that demonstrates the behavior you are seeing?

**Comment by nojaf** [comment]
Hmm, I believe that the problem is performance of the Windows container. Single record insert did work, so I'm guessing the actual error makes sense. The operation took too long and timed out.

When I switched to Linux container I had no problem whatsoever.
