### ISSUE TITLE
Input string was not in a correct format.

### ISSUE THREAD

**Issue by Taegos** [aspnet/EntityFramework6#661]
Adding an entity that is used in a one-to-many relationship produces:

Exception message: `System.FormatException : Input string was not in a correct format.`

Stack trace:  `at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Convert.ToDouble(String value)
   at MySql.Data.Entity.MySqlMigrationSqlGenerator.Generate(CreateIndexOperation op)
   at MySql.Data.Entity.MySqlMigrationSqlGenerator.Generate(IEnumerable`1 migrationOperations, String providerManifestToken)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
   at System.Data.Entity.Migrations.DbMigrator.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Internal.DatabaseCreator.CreateDatabase(InternalContext internalContext, Func`3 createMigrator, ObjectContext objectContext)
   at System.Data.Entity.Database.Create(DatabaseExistenceState existenceState)
   at System.Data.Entity.DropCreateDatabaseAlways`1.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)
   at System.Data.Entity.DbSet`1.Add(TEntity entity)
   at Data.Repos.Impl.ScheduleRepo.SetSchedule() in C:\Users\Benjamin\Desktop\uptrender\Data\Repos\Impl\ScheduleRepo.cs:line 18
   at Data.Tests.ScheduleRepoTest.TestSetSchedule() in C:\Users\Benjamin\Desktop\uptrender\Data\Tests\ScheduleRepoTest.cs:line 21`

### Steps to reproduce

```
    [TestFixture]
    public class ScheduleRepoTest {

        private readonly ScheduleRepo repo = new ScheduleRepo();

        [Test]
        public void TestSetSchedule()
        {
            repo.SetSchedule();     
        }
    }

    public class ScheduleRepo  {
        public void SetSchedule()
        {
            Schedule schedule = new Schedule();
            using (UptrenderDbContext ctx = new UptrenderDbContext())
            {
                ctx.Schedules.Add(schedule);
                ctx.SaveChanges();
            }
        }
    }

    public class Schedule
    {
        public int ScheduleId { get; set; }
    }

    public class Instruction
    {
        public string InstructionId { get; set; }
        public Schedule Schedule{ get; set; }
    }

    [DbConfigurationType(typeof(MySqlEFConfiguration))]
    public class UptrenderDbContext : DbContext
    {
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Instruction> Instructions { get; set; } //Not used yet

        public UptrenderDbContext() { 
            Database.SetInitializer(new DropCreateDatabaseAlways<UptrenderDbContext>());
        }
    }
```

App.config:

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <connectionStrings>
    <add name="UptrenderDbContext" providerName="MySql.Data.MySqlClient"
         connectionString="server=localhost;port=3306;database=uptrender_test;uid=root;password=thapassword"/>
  </connectionStrings>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.SqlConnectionFactory, EntityFramework"/>
    <providers>
      <provider invariantName="MySql.Data.MySqlClient"
                type="MySql.Data.MySqlClient.MySqlProviderServices, MySql.Data.Entity.EF6"/>
    </providers>
  </entityFramework>
</configuration>`

### Further technical details
EF version: 6.2.0
Database Provider: MySql.Data.MySqlClient
Operating system: Windows 10
IDE:  Visual Studio 2017 15.8
MySQL Server: 8.0.13
Connector/Net: 8.0.13
MySql.Data.Entity: 6.10.8
Mysql.Data: 6.10.8

**Comment by ajcvickers** [comment]
This issue is in the MySQL provider code. Please contact the authors of the provider.
