### ISSUE TITLE
Support Select with non-default constructor

### ISSUE THREAD

**Issue by mycroes** [aspnet/EntityFramework6#724]
Currently EF will throw a `NotSupportedException` when a `Select` contains a non-default (with parameters) constructor for a *declared* type.

```
System.NotSupportedException
  HResult=0x80131515
  Message=Only parameterless constructors and initializers are supported in LINQ to Entities.
  Source=EntityFramework
  StackTrace:
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.NewTranslator.TypedTranslate(ExpressionConverter parent, NewExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateLambda(LambdaExpression lambda, DbExpression input, DbExpressionBinding& binding)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.OneLambdaTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, DbExpression& source, DbExpressionBinding& sourceBinding, DbExpression& lambda)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.SelectTranslator.Translate(ExpressionConverter parent, MethodCallExpression call)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.SequenceMethodTranslator.Translate(ExpressionConverter parent, MethodCallExpression call, SequenceMethod sequenceMethod)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.MethodCallTranslator.TypedTranslate(ExpressionConverter parent, MethodCallExpression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TypedTranslator`1.Translate(ExpressionConverter parent, Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.TranslateExpression(Expression linq)
   at System.Data.Entity.Core.Objects.ELinq.ExpressionConverter.Convert()
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFSandbox.Program.Main() in C:\Users\michaelc\Documents\Projects\Sandbox\EFSandbox\EFSandbox\Program.cs:line 18
```

### Steps to reproduce

```c#
using System;
using System.Data.Entity;
using System.Linq;

namespace EFSandbox
{
    class Program
    {
        static void Main()
        {
            using (var context = new TestContext())
            {
                var res = context.Parents.Select(p => new Test(p.Id)).ToList();
                Console.WriteLine(string.Join(", ", res.Select(r => r.Value)));
            }
        }

        public class Parent
        {
            public int Id { get; set; }
        }

        public class TestContext : DbContext
        {
            public TestContext()
            {
                Database.SetInitializer(new DropCreateDatabaseAlways<TestContext>());
            }

            public DbSet<Parent> Parents { get; set; }
        }

        private class Test
        {
            public Test(int value)
            {
                Value = value;
            }

            public int Value { get; }
        }
    }
}
```

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.7

The culprit is in [Translator.cs](https://github.com/aspnet/EntityFramework6/blob/09de24305aabf309366f7cebd613c2a3cfcc587f/src/EntityFramework/Core/Objects/ELinq/Translator.cs#L842):
```c#
if (null == linq.Constructor
    ||
    linq.Arguments.Count != memberCount)
{
    throw new NotSupportedException(Strings.ELinq_UnsupportedConstructor);
}

parent.CheckInitializerType(linq.Type);

var recordColumns =
    new List<KeyValuePair<string, DbExpression>>(memberCount + 1);

var memberNames = new HashSet<string>(StringComparer.Ordinal);
for (var i = 0; i < memberCount; i++)
{
    string memberName;
    Type memberType;
    TypeSystem.PropertyOrField(linq.Members[i], out memberName, out memberType);
    var memberValue = parent.TranslateExpression(linq.Arguments[i]);
    memberNames.Add(memberName);
    recordColumns.Add(new KeyValuePair<string, DbExpression>(memberName, memberValue));
}
```

I'm not sure why EF wants to look up the members, which are present if you select into an *anonymous* type (which actually will have a non-default constructor with a parameter for every selected member). Instead of getting the name from the member, the name from the `ParameterInfo` could be used just as well. Alternatively, it's possible to lookup the member by convention based on the name from the parameter. The basic implementation to do this can be as follows:

```c#
       public static Expression<Func<TSource, TResult>> WithMembers<TSource, TResult>(this Expression<Func<TSource, TResult>> expression)
        {
            var body = expression.Body as NewExpression ??
                throw new ArgumentException($"Expression should be a {nameof(NewExpression)}.", nameof(expression));

            return expression.Update(body.WithMembers(), expression.Parameters);
        }

        public static NewExpression WithMembers(this NewExpression node)
        {
            if (node.Members != null) return node;

            var members = new MemberInfo[node.Arguments.Count];
            foreach (var param in node.Constructor.GetParameters())
            {
                var member = GetMember(node.Type, param.Name.UcFirst()) ??
                    throw new Exception($"No member found for constructor parameter {param.Name}.");

                members[param.Position] = member;
            }

            return Expression.New(node.Constructor, node.Arguments, members);
        }

        private static MemberInfo GetMember(Type type, string name)
        {
            var members = type.GetMember(name);
            return members.Length == 0 ? null : members[0];
        }

        private static string UcFirst(this string input)
        {
            return char.ToUpper(input[0]) + input.Substring(1);
        }
```

For my personal use I also created an `ExpressionVisitor` that can apply this to the query so that it also handles possibly more complex types.

I'd love to hear if there's any reason to stick to the current implementation, if not I'll gladly provide PR's for both possible solutions.

**Comment by ajcvickers** [comment]
**EF Team Triage:** This issue is not something that our team is planning to address in the EF6.x code base.  This does not mean that we would not consider a community contribution to address this issue.

Moving forwards, our team will be fixing bugs, implementing small improvements, and accepting community contributions to the EF6.x code base. Larger feature work and innovation will happen in the EF Core code base (https://github.com/aspnet/EntityFramework).

**Closing an issue in the EF6.x project does not exclude us addressing it in EF Core. In fact, a number of popular feature requests for EF have already been implemented in EF Core (alternate keys, batching in SaveChanges, etc.).**

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*
