### ISSUE TITLE
Cannot Add-Migration after moving configuration to use Microsoft.Extensions.Configuration (appsettings.json)

### ISSUE THREAD

**Issue by Jojoshua** [aspnet/EntityFramework6#831]
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
System.TypeInitializationException: The type initializer for 'System.Data.Entity.Migrations.DbMigrationsConfiguration`1' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Data.Entity.Internal.AppConfig' threw an exception. ---> System.Configuration.ConfigurationErrorsException: An error occurred loading a configuration file: Could not load file or assembly 'MOVIES' or one of its dependencies. The system cannot find the file specified. (C:\Users\UID\Downloads\movies\movies\MOVIES\tmpEB8.tmp line 72) ---> System.IO.FileNotFoundException: Could not load file or assembly 'MOVIES' or one of its dependencies. The system cannot find the file specified.
   at System.Configuration.TypeUtil.GetTypeImpl(String typeString, Boolean throwOnError)
   at System.Configuration.ConfigurationBuildersSection.InstantiateBuilder(ProviderSettings ps)
   at System.Configuration.ConfigurationBuildersSection.GetBuilderFromName(String builderName)
   at System.Configuration.BaseConfigurationRecord.GetConfigBuilderFromName(String builderName)
   at System.Configuration.BaseConfigurationRecord.GetSectionXmlReader(String[] keys, SectionInput input)
   --- End of inner exception stack trace ---
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.get_ConnectionStrings()
   at System.Data.Entity.Internal.AppConfig..ctor()
   at System.Data.Entity.Internal.AppConfig..cctor()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Infrastructure.DependencyResolution.DbConfigurationManager.EnsureLoadedForAssembly(Assembly assemblyHint, Type contextTypeHint)
   at System.Data.Entity.Infrastructure.DependencyResolution.DbConfigurationManager.EnsureLoadedForContext(Type contextType)
   at System.Data.Entity.Migrations.DbMigrationsConfiguration`1..cctor()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Migrations.DbMigrationsConfiguration`1..ctor()
   at MOVIES.Data.Migrations.Configuration..ctor() in C:\Users\UID\Downloads\movies\movies\MOVIES.Data\Migrations\Configuration.cs:line 12
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Data.Entity.Migrations.Utilities.MigrationsConfigurationFinder.FindMigrationsConfiguration(Type contextType, String configurationTypeName, Func`2 noType, Func`3 multipleTypes, Func`3 noTypeWithName, Func`3 multipleTypesWithName)
   at System.Data.Entity.Migrations.Design.ToolingFacade.BaseRunner.FindConfiguration()
   at System.Data.Entity.Migrations.Design.ToolingFacade.ScaffoldRunner.RunCore()
   at System.Data.Entity.Migrations.Design.ToolingFacade.BaseRunner.Run()
The type initializer for 'System.Data.Entity.Migrations.DbMigrationsConfiguration`1' threw an exception.
```

### Steps to reproduce
I have an ASP.NET MVC 5 application and was using the standard appsettings in the web.config. However, I just moved my configuration to use Microsoft.Extensions.Configuration and followed this article to do so. My code is similar. https://dasmulli.blog/2018/01/21/use-appsettings-json-and-environment-overrides-in-classic-asp-net-apps/

This works as expected in my application ...until I tried to do an Add-Migration. Above is the error. I have my main ASP.NET in project called MOVIES and a MOVIES.Data project as my DAL and is where my migrations sit.

The relevant items in web.config are below. As soon as I revert back to using the xml settings, I don't get the error. Also to be clear, it is only Add-Migration that is giving the error. My application loads and uses the connection strings fine.
```
<configuration>
	<configSections>
		<section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />		
    <section name="configBuilders" type="System.Configuration.ConfigurationBuildersSection, System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" restartOnExternalChanges="false" requirePermission="false" />
  <configBuilders>
    <builders>
      <add name="AppSettingsJsonConfigurationBuilder" type="MOVIES.AppSettingsJsonConfigurationBuilder, MOVIES" />
    </builders>
  </configBuilders>
  
	<!--<appSettings configSource="WebConfig\appSettings.xml" />-->
  <appSettings configBuilders="AppSettingsJsonConfigurationBuilder" />

  <connectionStrings configBuilders="AppSettingsJsonConfigurationBuilder">
    <clear/>
  </connectionStrings>

```

### Further technical details
EF version: 6.2.0
Database Provider:  EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.8

**Comment by Jojoshua** [comment]
The main difference is toggling the connection strings. Using xml works and the configBuilder does not.

  
  <connectionStrings configBuilders="AppSettingsJsonConfigurationBuilder"/>

**Comment by Jojoshua** [comment]
Found out if I change the type to MOVIES.Data this now works. I'm not sure if this an issue with package manager console (I have MOVIES.Data selected as the default project when adding the migration), entity framework, configuration extensions, or my project setup. I would prefer to keep the AppSettingsJsonConfigurationBuilder code inside the MOVIES project. Any ideas?

```
 <configBuilders>
    <builders>
      <add name="AppSettingsJsonConfigurationBuilder" type="MOVIES.AppSettingsJsonConfigurationBuilder, MOVIES.Data" />
    </builders>
  </configBuilders>
```

**Comment by ajcvickers** [comment]
EF6 supports `web.config`/`app.config` for file-based configuration, or `DbConfiguration` for code-based configuration. EF6 doesn't support any of the new json files.

**Comment by Jojoshua** [comment]
I actually ended up making this work with the new json files using some code.

**Comment by Jojoshua** [comment]
@ajcvickers , I got this to work using ConfigurationBuilder but can the json configuration be officially supported in 6.3?

**Comment by ajcvickers** [comment]
@Jojoshua We do not plan to evolve the EF6 code base significantly. The changes we made were to allow EF6 to be used on .NET Core in order to help people port existing applications to .NET Core. We're not planning to change the way EF6 works as part of this.
