### ISSUE TITLE
IndexOutOfRangeException when compiling query with multiple Concat()

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework6#861]
Run the following code on EF6 6.3.0-preview5-19254-05 on netcoreapp3.0:

```c#
class Program
{
    private const string ConnectionString = "...";

    static void Main(string[] args)
    {
        DbProviderFactories.RegisterFactory("System.Data.SqlClient", SqlClientFactory.Instance);

        using (var ctx = new BloggingContext(ConnectionString))
        {
            var blogs = ctx.Blogs.Concat(ctx.Blogs).Concat(ctx.Blogs.Concat(ctx.Blogs)).ToArray();
        }
    }
}

public class Blog
{
    public int BlogId { get; set; }
    public string Name { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public int IntComputedValue { get; set; }
}

public class User
{
    public int Id { get; set; }

    public IList<Blog> Blogs { get; set; }
}

public class BloggingContext : DbContext
{
    public BloggingContext(string connection)
        : base(connection)
    {
    }

    public DbSet<Blog> Blogs { get; set; }
    public DbSet<User> Users { get; set; }
}
```

This throws the following:

```
Unhandled Exception: System.Data.Entity.Core.EntityCommandCompilationException: An error occurred while preparing the command definition. See the inner exception for details. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.BitArray.Or(BitArray value)
   at System.Data.Entity.Core.Query.InternalTrees.VarVec.InitFrom(VarVec other)
   at System.Data.Entity.Core.Query.InternalTrees.Command.CreateVarVec(VarVec v)
   at System.Data.Entity.Core.Query.InternalTrees.NodeInfoVisitor.Visit(ProjectOp op, Node n)
   at System.Data.Entity.Core.Query.InternalTrees.NodeInfoVisitor.RecomputeNodeInfo(Node n)
   at System.Data.Entity.Core.Query.InternalTrees.Node.GetExtendedNodeInfo(Command command)
   at System.Data.Entity.Core.Query.InternalTrees.NodeInfoVisitor.VisitSetOp(SetOp op, Node n)
   at System.Data.Entity.Core.Query.InternalTrees.NodeInfoVisitor.RecomputeNodeInfo(Node n)
   at System.Data.Entity.Core.Query.InternalTrees.Node.GetExtendedNodeInfo(Command command)
   at System.Data.Entity.Core.Query.InternalTrees.NodeInfoVisitor.VisitSetOp(SetOp op, Node n)
   at System.Data.Entity.Core.Query.InternalTrees.NodeInfoVisitor.RecomputeNodeInfo(Node n)
   at System.Data.Entity.Core.Query.InternalTrees.Node.GetExtendedNodeInfo(Command command)
   at System.Data.Entity.Core.Query.InternalTrees.NodeInfoVisitor.Visit(ProjectOp op, Node n)
   at System.Data.Entity.Core.Query.InternalTrees.NodeInfoVisitor.RecomputeNodeInfo(Node n)
   at System.Data.Entity.Core.Query.InternalTrees.NodeInfoVisitor.Visit(PhysicalProjectOp op, Node n)
   at System.Data.Entity.Core.Query.InternalTrees.NodeInfoVisitor.RecomputeNodeInfo(Node n)
   at System.Data.Entity.Core.Query.InternalTrees.Command.GetNodeInfo(Node n)
   at System.Data.Entity.Core.Query.PlanCompiler.TransformationRulesContext.GetHashCode(Node node)
   at System.Data.Entity.Core.Query.InternalTrees.RuleProcessor.ApplyRulesToSubtree(RuleProcessingContext context, ReadOnlyCollection`1 rules, Node subTreeRoot, Node parent, Int32 childIndexInParent)
   at System.Data.Entity.Core.Query.PlanCompiler.TransformationRules.Process(PlanCompiler compilerState, ReadOnlyCollection`1 rulesTable, Boolean& projectionPruningRequired)
   at System.Data.Entity.Core.Query.PlanCompiler.TransformationRules.Process(PlanCompiler compilerState, TransformationRulesGroup rulesGroup)
   at System.Data.Entity.Core.Query.PlanCompiler.PlanCompiler.Compile(List`1& providerCommands, ColumnMap& resultColumnMap, Int32& columnCount, Set`1& entitySets)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition..ctor(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver, BridgeDataReaderFactory bridgeDataReaderFactory, ColumnMapFactory columnMapFactory)
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition..ctor(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver, BridgeDataReaderFactory bridgeDataReaderFactory, ColumnMapFactory columnMapFactory)
   at System.Data.Entity.Core.EntityClient.Internal.EntityProviderServices.CreateDbCommandDefinition(DbProviderManifest providerManifest, DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.CreateCommandDefinition(ObjectContext context, DbQueryCommandTree tree)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.Prepare(ObjectContext context, DbQueryCommandTree tree, Type elementType, MergeOption mergeOption, Boolean streaming, Span span, IEnumerable`1 compiledQueryParameters, AliasGenerator aliasGenerator)
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.<GetResults>b__1()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__31_0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Test.Program.Main(String[] args) in /home/roji/projects/Test/Program.cs:line 33
```

The multiple concats are required, as well as the computed column and the User entity referencing Blog...

/cc @bricelam

**Comment by bricelam** [comment]
dotnet/corefx#37849

**Comment by roji** [comment]
Confirmed that the relevant Npgsql EF6 tests now pass.
